slogan: "while(true){eat(); sleep(); code();}"

headline:
  - "Welcome ~ ヾ (o ° ω ° O ) ノ゙"
  - "Go for it ~ ヽ(•̀ω•́ )ゝ"
  - "Am i cute ? (○’ω’○) "
  - "Come on ~ (╭￣3￣)╭"
  - "Sleepy ... ≡￣﹏￣≡ "
  - "I'm very shy(/ω＼) ... (/ω・＼) ... (/・ω・＼)"
  - "HaHaHa .. o(*≧▽≦)ツ┏━┓"
  - "I'm hungry~ ∑(っ °Д °;)っ "
  - "( ゜- ゜)つロ Cheers ~"

menu:
  - title: Archives
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: Categories
    url: categories
    intro: "All the categories."
    icon: "fa fa-folder"
  - title: Tags
    url: tags
    intro: "All the tags."
    icon: "fa fa-tags"
  - title: About
    url: about
    intro: "About me."
    icon: "fa fa-user"

links:
  - title: "Github-PytLab"
    url: https://github.com/PytLab
    intro: "My Github account."
    icon: "fa fa-github"
  - title: "Weibo-PytLab"
    url: http://weibo.com/shaowugui 
    intro: "My Weibo account."
    icon: "fa fa-weibo"
  - title: "Email"
    url: mailto:shaozhengjiang@gmail.com
    intro: "Send Email to me"
    icon: "fa fa-mail-forward"
  - title: "StackOverflow-PytLab"
    url: http://stackoverflow.com/users/4014840/pytlab
    intro: "My StackOverflow account"
    icon: "fa fa-stack-overflow"
  - title: "Hexo Repo"
    url: https://github.com/hexojs/hexo
    icon: "fa fa-code-fork"
  - title: "Freemind Repo"
    url: https://github.com/wzpan/hexo-theme-freemind
    icon: "fa fa-code-fork"
  - title: "My Freemind Repo"
    intro: "Freemind theme customized by Me"
    url: https://github.com/PytLab/hexo-theme-freemind
    icon: "fa fa-code-fork"
  

widgets:
- search
- recent_posts  
- category
- tagcloud
- links

rss: 
fancybox: true
favicon: favicon.png
duoshuo_shortname: pytlab

# Analytics
google_analytics:
  enable: false
  siteid:
baidu_tongji:
  enable: true
  siteid: pytlab.github.io

# search
# swiftype_key: ZP2ZSuHgipSZfRyU8uTR
